name: My CI # give name for this *.yml file

on: # This *.yml file executes the jobs whenever the command below 'push' is executed
  push:
    branches: [main] # jobs below are run when push to main branch is made
  pull_request:
  workflow_dispatch:

jobs:
  hello:
    name: Hello job
    runs-on: ubuntu-latest # specify which platform to run the steps on
    steps:
      - name: My first step
        run: echo "Hello World!"

  test:
    name: Run tests
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.14']
    steps:
      - name: Check out repo # without this, as CI starts with blank repo, it never locates pyproject.toml file
        uses: actions/checkout@v6 # github action: can be actions/checkout@[v6,branch_name]
      - name: Install Python 
        uses: actions/setup-python@v6 # install specific version of Python package
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python package
        run: pip install .[test] # comes from pyproject.toml
      - name: Run test
        run: pytest -vv # verbose as possible
