name: My CI # give name for this *.yml file

on: # This *.yml file executes the jobs whenever the command below 'push' is executed
  push:
    branches: [main] # jobs below are run when push to main branch is made

jobs:
  hello:
    name: Hello job
    runs-on: ubuntu-latest # specify which platform to run the steps on
    steps:
      - name: My first step
        run: echo "Hello World!"

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Python package
        run: pip install .[test] # comes from pyproject.yoml
      - name: Run test
        run: pytest -vv # verbose as possible
